/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestContract1 } from "./TestContract1";
export * as factories from "./factories";
export { TestContract1__factory } from "./factories/TestContract1__factory";
