
networks:
  location-network:
secrets:                        
  REMOTE_NODE_ENDPOINT:
    file: REMOTE_NODE_ENDPOINT.txt
  user0_pw:
    file: user0_pw.txt
  user1_pw:
    file: user1_pw.txt
  db_connection_string:
    file: db_connection_string.txt
