/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myErc20Sol from "./myERC20.sol";
export { TestContract1__factory } from "./TestContract1__factory";
