/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myErc20Sol from "./myERC20.sol";
export type { myErc20Sol };
export type { TestContract1 } from "./TestContract1";
